### PR TITLE
Add tox.ini and setup.py

### LINKED ISSUE #6: Add tox.ini
Test on different versions of Python, flake8 and all of that

### PR DESCRIPTION
**Pull request by davide-ceretti**
Fixes https://github.com/raulcd/meteora/issues/6

### CODE REVIEW

**Comment by raulcd** [comment]
@davide-ceretti nice changes but why are you removing requirements.txt?

**Comment by davide-ceretti** [comment]
I specified the requirements at https://github.com/raulcd/meteora/pull/10/files#diff-2eeaed663bd0d25b7e608891384b7298R10. I can change that and read from requirements.txt instead if you like, but I don't think it's necessary,

**Comment by davide-ceretti** [comment]
See how it works with Flask (https://github.com/mitsuhiko/flask/blob/master/setup.py#L71) for example.

**Comment by raulcd** [comment]
No, it does make sense with the pip install -e .

**Pull request merged**
